// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket
{

public enum PacketType : sbyte
{
  None = 0,
  Sign_In = 1,
  Sign_Up = 2,
  User_Information = 3,
  Attendance_Sheets = 4,
  Attendance_Check = 5,
  MailsInfo = 6,
  MailConfirm = 7,
  MailReceive = 8,
  ReceivedRewards = 9,
  DB_Sign_In = 10,
  DB_Sign_Up = 11,
  DB_User_Information = 12,
  DB_Attendance_Sheets = 13,
  DB_Attendance_Check = 14,
  DB_MailConfirm = 15,
  DB_MailReceive = 16,
  DB_CheckExpiredMails = 17,
  DB_MailsInfo = 18,
  Error = 19,
  Disconnect = 20,
  JsonDownloadStartPacket = 21,
  JsonDownloadingPacket = 22,
  JsonDownloadEndPacket = 25,
};


}
