// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket
{

public enum RequestMessageType : sbyte
{
  None = 0,
  Succeeded = 1,
  Failed = 2,
};


}
