// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.JsonPacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JsonDownloadNotifyPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JsonDownloadNotifyPacket GetRootAsJsonDownloadNotifyPacket(ByteBuffer _bb) { return GetRootAsJsonDownloadNotifyPacket(_bb, new JsonDownloadNotifyPacket()); }
  public static JsonDownloadNotifyPacket GetRootAsJsonDownloadNotifyPacket(ByteBuffer _bb, JsonDownloadNotifyPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyJsonDownloadNotifyPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, JsonDownloadNotifyPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JsonDownloadNotifyPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long OriginalJsonLength { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CompressedJsonLength { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatPacket.JsonPacket.JsonDownloadNotifyPacket> CreateJsonDownloadNotifyPacket(FlatBufferBuilder builder,
      long original_json_length = 0,
      long compressed_json_length = 0) {
    builder.StartTable(2);
    JsonDownloadNotifyPacket.AddCompressedJsonLength(builder, compressed_json_length);
    JsonDownloadNotifyPacket.AddOriginalJsonLength(builder, original_json_length);
    return JsonDownloadNotifyPacket.EndJsonDownloadNotifyPacket(builder);
  }

  public static void StartJsonDownloadNotifyPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddOriginalJsonLength(FlatBufferBuilder builder, long originalJsonLength) { builder.AddLong(0, originalJsonLength, 0); }
  public static void AddCompressedJsonLength(FlatBufferBuilder builder, long compressedJsonLength) { builder.AddLong(1, compressedJsonLength, 0); }
  public static Offset<FlatPacket.JsonPacket.JsonDownloadNotifyPacket> EndJsonDownloadNotifyPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatPacket.JsonPacket.JsonDownloadNotifyPacket>(o);
  }
  public static void FinishJsonDownloadNotifyPacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.JsonPacket.JsonDownloadNotifyPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedJsonDownloadNotifyPacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.JsonPacket.JsonDownloadNotifyPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class JsonDownloadNotifyPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*OriginalJsonLength*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*CompressedJsonLength*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
