// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatInGamePacket.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinGamePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JoinGamePacket GetRootAsJoinGamePacket(ByteBuffer _bb) { return GetRootAsJoinGamePacket(_bb, new JoinGamePacket()); }
  public static JoinGamePacket GetRootAsJoinGamePacket(ByteBuffer _bb, JoinGamePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyJoinGamePacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, JoinGamePacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinGamePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatInGamePacket.Game.UserSpawnInfo? JoinedUsers(int j) { int o = __p.__offset(4); return o != 0 ? (FlatInGamePacket.Game.UserSpawnInfo?)(new FlatInGamePacket.Game.UserSpawnInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int JoinedUsersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatInGamePacket.Game.JoinGamePacket> CreateJoinGamePacket(FlatBufferBuilder builder,
      VectorOffset joined_usersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    JoinGamePacket.AddJoinedUsers(builder, joined_usersOffset);
    return JoinGamePacket.EndJoinGamePacket(builder);
  }

  public static void StartJoinGamePacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddJoinedUsers(FlatBufferBuilder builder, VectorOffset joinedUsersOffset) { builder.AddOffset(0, joinedUsersOffset.Value, 0); }
  public static VectorOffset CreateJoinedUsersVector(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.UserSpawnInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateJoinedUsersVectorBlock(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.UserSpawnInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateJoinedUsersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatInGamePacket.Game.UserSpawnInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateJoinedUsersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatInGamePacket.Game.UserSpawnInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartJoinedUsersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatInGamePacket.Game.JoinGamePacket> EndJoinGamePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatInGamePacket.Game.JoinGamePacket>(o);
  }
  public static void FinishJoinGamePacketBuffer(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.JoinGamePacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedJoinGamePacketBuffer(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.JoinGamePacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class JoinGamePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*JoinedUsers*/, FlatInGamePacket.Game.UserSpawnInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
