// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatInGamePacket.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerGameDataPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerGameDataPacket GetRootAsPlayerGameDataPacket(ByteBuffer _bb) { return GetRootAsPlayerGameDataPacket(_bb, new PlayerGameDataPacket()); }
  public static PlayerGameDataPacket GetRootAsPlayerGameDataPacket(ByteBuffer _bb, PlayerGameDataPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPlayerGameDataPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PlayerGameDataPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerGameDataPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatInGamePacket.Game.VehicleInformation? VehicleTransform { get { int o = __p.__offset(6); return o != 0 ? (FlatInGamePacket.Game.VehicleInformation?)(new FlatInGamePacket.Game.VehicleInformation()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FlatInGamePacket.Game.PlayerGameDataPacket> CreatePlayerGameDataPacket(FlatBufferBuilder builder,
      int uuid = 0,
      Offset<FlatInGamePacket.Game.VehicleInformation> vehicle_transformOffset = default(Offset<FlatInGamePacket.Game.VehicleInformation>)) {
    builder.StartTable(2);
    PlayerGameDataPacket.AddVehicleTransform(builder, vehicle_transformOffset);
    PlayerGameDataPacket.AddUuid(builder, uuid);
    return PlayerGameDataPacket.EndPlayerGameDataPacket(builder);
  }

  public static void StartPlayerGameDataPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddVehicleTransform(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.VehicleInformation> vehicleTransformOffset) { builder.AddOffset(1, vehicleTransformOffset.Value, 0); }
  public static Offset<FlatInGamePacket.Game.PlayerGameDataPacket> EndPlayerGameDataPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatInGamePacket.Game.PlayerGameDataPacket>(o);
  }
  public static void FinishPlayerGameDataPacketBuffer(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.PlayerGameDataPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPlayerGameDataPacketBuffer(FlatBufferBuilder builder, Offset<FlatInGamePacket.Game.PlayerGameDataPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PlayerGameDataPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Uuid*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*VehicleTransform*/, FlatInGamePacket.Game.VehicleInformationVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
