// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatInGamePacket.Game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UserSpawnInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static UserSpawnInfo GetRootAsUserSpawnInfo(ByteBuffer _bb) { return GetRootAsUserSpawnInfo(_bb, new UserSpawnInfo()); }
  public static UserSpawnInfo GetRootAsUserSpawnInfo(ByteBuffer _bb, UserSpawnInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserSpawnInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string UserName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUserNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUserNameArray() { return __p.__vector_as_array<byte>(6); }
  public short SpawnIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<FlatInGamePacket.Game.UserSpawnInfo> CreateUserSpawnInfo(FlatBufferBuilder builder,
      int uuid = 0,
      StringOffset user_nameOffset = default(StringOffset),
      short spawn_index = 0) {
    builder.StartTable(3);
    UserSpawnInfo.AddUserName(builder, user_nameOffset);
    UserSpawnInfo.AddUuid(builder, uuid);
    UserSpawnInfo.AddSpawnIndex(builder, spawn_index);
    return UserSpawnInfo.EndUserSpawnInfo(builder);
  }

  public static void StartUserSpawnInfo(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddUserName(FlatBufferBuilder builder, StringOffset userNameOffset) { builder.AddOffset(1, userNameOffset.Value, 0); }
  public static void AddSpawnIndex(FlatBufferBuilder builder, short spawnIndex) { builder.AddShort(2, spawnIndex, 0); }
  public static Offset<FlatInGamePacket.Game.UserSpawnInfo> EndUserSpawnInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatInGamePacket.Game.UserSpawnInfo>(o);
  }
}


static public class UserSpawnInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Uuid*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*UserName*/, false)
      && verifier.VerifyField(tablePos, 8 /*SpawnIndex*/, 2 /*short*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
