// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.SessionPacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JosinSession : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JosinSession GetRootAsJosinSession(ByteBuffer _bb) { return GetRootAsJosinSession(_bb, new JosinSession()); }
  public static JosinSession GetRootAsJosinSession(ByteBuffer _bb, JosinSession obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyJosinSession(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, JosinSessionVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JosinSession __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatPacket.SessionPacket.session_information? SessionInfo { get { int o = __p.__offset(4); return o != 0 ? (FlatPacket.SessionPacket.session_information?)(new FlatPacket.SessionPacket.session_information()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FlatPacket.SessionPacket.JosinSession> CreateJosinSession(FlatBufferBuilder builder,
      Offset<FlatPacket.SessionPacket.session_information> session_infoOffset = default(Offset<FlatPacket.SessionPacket.session_information>)) {
    builder.StartTable(1);
    JosinSession.AddSessionInfo(builder, session_infoOffset);
    return JosinSession.EndJosinSession(builder);
  }

  public static void StartJosinSession(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSessionInfo(FlatBufferBuilder builder, Offset<FlatPacket.SessionPacket.session_information> sessionInfoOffset) { builder.AddOffset(0, sessionInfoOffset.Value, 0); }
  public static Offset<FlatPacket.SessionPacket.JosinSession> EndJosinSession(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatPacket.SessionPacket.JosinSession>(o);
  }
  public static void FinishJosinSessionBuffer(FlatBufferBuilder builder, Offset<FlatPacket.SessionPacket.JosinSession> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedJosinSessionBuffer(FlatBufferBuilder builder, Offset<FlatPacket.SessionPacket.JosinSession> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class JosinSessionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*SessionInfo*/, FlatPacket.SessionPacket.session_informationVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
