// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.SessionPacket
{

public enum SessionRequestType : sbyte
{
  ESRT_None = 0,
  ESRT_Ready = 1,
  ESRT_NotReady = 2,
  ESRT_Chat = 3,
  ESRT_Start = 4,
  ESRT_Quit = 5,
};


}
