// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERGAMEDATAPACKET_FLATINGAMEPACKET_GAME_H_
#define FLATBUFFERS_GENERATED_PLAYERGAMEDATAPACKET_FLATINGAMEPACKET_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "vehicle_information_generated.h"

namespace FlatInGamePacket {
namespace Game {

struct PlayerGameDataPacket;
struct PlayerGameDataPacketBuilder;

struct PlayerGameDataPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerGameDataPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UUID = 4,
    VT_VEHICLE_TRANSFORM = 6
  };
  int32_t uuid() const {
    return GetField<int32_t>(VT_UUID, 0);
  }
  const FlatInGamePacket::Game::VehicleInformation *vehicle_transform() const {
    return GetPointer<const FlatInGamePacket::Game::VehicleInformation *>(VT_VEHICLE_TRANSFORM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_UUID, 4) &&
           VerifyOffset(verifier, VT_VEHICLE_TRANSFORM) &&
           verifier.VerifyTable(vehicle_transform()) &&
           verifier.EndTable();
  }
};

struct PlayerGameDataPacketBuilder {
  typedef PlayerGameDataPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uuid(int32_t uuid) {
    fbb_.AddElement<int32_t>(PlayerGameDataPacket::VT_UUID, uuid, 0);
  }
  void add_vehicle_transform(::flatbuffers::Offset<FlatInGamePacket::Game::VehicleInformation> vehicle_transform) {
    fbb_.AddOffset(PlayerGameDataPacket::VT_VEHICLE_TRANSFORM, vehicle_transform);
  }
  explicit PlayerGameDataPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerGameDataPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerGameDataPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerGameDataPacket> CreatePlayerGameDataPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t uuid = 0,
    ::flatbuffers::Offset<FlatInGamePacket::Game::VehicleInformation> vehicle_transform = 0) {
  PlayerGameDataPacketBuilder builder_(_fbb);
  builder_.add_vehicle_transform(vehicle_transform);
  builder_.add_uuid(uuid);
  return builder_.Finish();
}

inline const FlatInGamePacket::Game::PlayerGameDataPacket *GetPlayerGameDataPacket(const void *buf) {
  return ::flatbuffers::GetRoot<FlatInGamePacket::Game::PlayerGameDataPacket>(buf);
}

inline const FlatInGamePacket::Game::PlayerGameDataPacket *GetSizePrefixedPlayerGameDataPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FlatInGamePacket::Game::PlayerGameDataPacket>(buf);
}

inline bool VerifyPlayerGameDataPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FlatInGamePacket::Game::PlayerGameDataPacket>(nullptr);
}

inline bool VerifySizePrefixedPlayerGameDataPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FlatInGamePacket::Game::PlayerGameDataPacket>(nullptr);
}

inline void FinishPlayerGameDataPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FlatInGamePacket::Game::PlayerGameDataPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerGameDataPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FlatInGamePacket::Game::PlayerGameDataPacket> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Game
}  // namespace FlatInGamePacket

#endif  // FLATBUFFERS_GENERATED_PLAYERGAMEDATAPACKET_FLATINGAMEPACKET_GAME_H_
