// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatInGamePacket
{

public enum PacketType : sbyte
{
  None = 0,
  Join = 1,
  Ready = 2,
  Start = 3,
  GameData = 4,
  HeartBeat = 5,
};


}
