// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.AttendancePacket
{

public enum AttendanceCheckMessageType : sbyte
{
  None = 0,
  TodayAttendance = 1,
  NextDayAttendance = 2,
  LeftAllDayAttendance = 3,
};


}
