// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.AttendancePacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AttendanceSheetsPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static AttendanceSheetsPacket GetRootAsAttendanceSheetsPacket(ByteBuffer _bb) { return GetRootAsAttendanceSheetsPacket(_bb, new AttendanceSheetsPacket()); }
  public static AttendanceSheetsPacket GetRootAsAttendanceSheetsPacket(ByteBuffer _bb, AttendanceSheetsPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAttendanceSheetsPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AttendanceSheetsPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AttendanceSheetsPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short RequestResult { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public int Uuid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public short RequestedEventType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public FlatPacket.AttendancePacket.AttendanceDetail? AttendanceSheets(int j) { int o = __p.__offset(10); return o != 0 ? (FlatPacket.AttendancePacket.AttendanceDetail?)(new FlatPacket.AttendancePacket.AttendanceDetail()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AttendanceSheetsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatPacket.AttendancePacket.AttendanceSheetsPacket> CreateAttendanceSheetsPacket(FlatBufferBuilder builder,
      short request_result = 0,
      int uuid = 0,
      short requested_event_type = 0,
      VectorOffset attendance_sheetsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    AttendanceSheetsPacket.AddAttendanceSheets(builder, attendance_sheetsOffset);
    AttendanceSheetsPacket.AddUuid(builder, uuid);
    AttendanceSheetsPacket.AddRequestedEventType(builder, requested_event_type);
    AttendanceSheetsPacket.AddRequestResult(builder, request_result);
    return AttendanceSheetsPacket.EndAttendanceSheetsPacket(builder);
  }

  public static void StartAttendanceSheetsPacket(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddRequestResult(FlatBufferBuilder builder, short requestResult) { builder.AddShort(0, requestResult, 0); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(1, uuid, 0); }
  public static void AddRequestedEventType(FlatBufferBuilder builder, short requestedEventType) { builder.AddShort(2, requestedEventType, 0); }
  public static void AddAttendanceSheets(FlatBufferBuilder builder, VectorOffset attendanceSheetsOffset) { builder.AddOffset(3, attendanceSheetsOffset.Value, 0); }
  public static VectorOffset CreateAttendanceSheetsVector(FlatBufferBuilder builder, Offset<FlatPacket.AttendancePacket.AttendanceDetail>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAttendanceSheetsVectorBlock(FlatBufferBuilder builder, Offset<FlatPacket.AttendancePacket.AttendanceDetail>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttendanceSheetsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatPacket.AttendancePacket.AttendanceDetail>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttendanceSheetsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatPacket.AttendancePacket.AttendanceDetail>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAttendanceSheetsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatPacket.AttendancePacket.AttendanceSheetsPacket> EndAttendanceSheetsPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatPacket.AttendancePacket.AttendanceSheetsPacket>(o);
  }
  public static void FinishAttendanceSheetsPacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.AttendancePacket.AttendanceSheetsPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAttendanceSheetsPacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.AttendancePacket.AttendanceSheetsPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AttendanceSheetsPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*RequestResult*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*Uuid*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RequestedEventType*/, 2 /*short*/, 2, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*AttendanceSheets*/, FlatPacket.AttendancePacket.AttendanceDetailVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
