// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket
{

public enum PacketType : sbyte
{
  None = 0,
  Sign_In = 1,
  Sign_Up = 2,
  User_Information = 3,
  Attendance_Sheets = 4,
  Attendance_Check = 5,
  Get_Inventory = 6,
  MailsInfo = 7,
  MailConfirm = 8,
  MailReceive = 9,
  ReceivedRewards = 10,
  DB_Sign_In = 11,
  DB_Sign_Up = 12,
  DB_User_Information = 13,
  DB_Attendance_Sheets = 14,
  DB_Attendance_Check = 15,
  DB_Get_Inventory = 16,
  DB_MailConfirm = 17,
  DB_MailReceive = 18,
  DB_CheckExpiredMails = 19,
  DB_MailsInfo = 20,
  Error = 21,
  JsonDownloadStartPacket = 22,
  JsonDownloadingPacket = 23,
  JsonDownloadEndPacket = 24,
};


}
