// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Mail
{

public enum RequestType : sbyte
{
  None = 0,
  Start = 1,
  Loop = 2,
  Stop = 3,
};


}
