// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket.Error
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ErrorMessagePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ErrorMessagePacket GetRootAsErrorMessagePacket(ByteBuffer _bb) { return GetRootAsErrorMessagePacket(_bb, new ErrorMessagePacket()); }
  public static ErrorMessagePacket GetRootAsErrorMessagePacket(ByteBuffer _bb, ErrorMessagePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyErrorMessagePacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ErrorMessagePacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ErrorMessagePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Message { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(4); }
  public bool CriticalError { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<FlatPacket.Error.ErrorMessagePacket> CreateErrorMessagePacket(FlatBufferBuilder builder,
      StringOffset messageOffset = default(StringOffset),
      bool critical_error = false) {
    builder.StartTable(2);
    ErrorMessagePacket.AddMessage(builder, messageOffset);
    ErrorMessagePacket.AddCriticalError(builder, critical_error);
    return ErrorMessagePacket.EndErrorMessagePacket(builder);
  }

  public static void StartErrorMessagePacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(0, messageOffset.Value, 0); }
  public static void AddCriticalError(FlatBufferBuilder builder, bool criticalError) { builder.AddBool(1, criticalError, false); }
  public static Offset<FlatPacket.Error.ErrorMessagePacket> EndErrorMessagePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatPacket.Error.ErrorMessagePacket>(o);
  }
  public static void FinishErrorMessagePacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.Error.ErrorMessagePacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedErrorMessagePacketBuffer(FlatBufferBuilder builder, Offset<FlatPacket.Error.ErrorMessagePacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ErrorMessagePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Message*/, false)
      && verifier.VerifyField(tablePos, 6 /*CriticalError*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
