// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatPacket
{

public enum PacketType : sbyte
{
  None = 0,
  Sign_In = 1,
  Sign_Up = 2,
  User_Information = 3,
  Attendance_Sheets = 4,
  Attendance_Check = 5,
  MailsInfo = 6,
  MailConfirm = 7,
  MailReceive = 8,
  ReceivedRewards = 9,
  FindSession = 10,
  CreateSession = 11,
  JoinSession = 12,
  QuitSession = 13,
  DB_Sign_In = 14,
  DB_Sign_Up = 15,
  DB_User_Information = 16,
  DB_Attendance_Sheets = 17,
  DB_Attendance_Check = 18,
  DB_MailConfirm = 19,
  DB_MailReceive = 20,
  DB_CheckExpiredMails = 21,
  DB_MailsInfo = 22,
  Error = 23,
  Disconnect = 24,
  JsonDownloadStartPacket = 25,
  JsonDownloadingPacket = 26,
  JsonDownloadEndPacket = 27,
};


}
